preload = /home/michka/perso/wallpaper/left_1920x1080.png
preload = /home/michka/perso/wallpaper/right_1920x1080.png

wallpaper = DP-2,/home/michka/perso/wallpaper/left_1920x1080.png
wallpaper = HDMI-A-2,/home/michka/perso/wallpaper/right_1920x1080.png